# Generated by Django 3.2.13 on 2023-04-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='perguntas/'),
        ),
    ]
