# Generated by Django 3.2.13 on 2023-04-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0002_pergunta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/perguntas/'),
        ),
    ]
