# Generated by Django 3.2.18 on 2023-05-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0003_alter_pergunta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.TextField(),
        ),
    ]
