# Generated by Django 3.2.18 on 2023-06-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0004_alter_pergunta_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='prova',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='provas.prova'),
        ),
    ]
